name: Test

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/FUNDING.YML'
      - '.github/dependabot.yml'
      - '**/*.md'
      - '.gitconfig'
      - '.gitignore'
      - '.npmignore'
      - 'LICENSE*'
      - '.idea/**'
      - '.vscode/**'
      - 'README.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: test-${{ matrix.os }}
    permissions:
      checks: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        # os: [macos-latest, ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ matrix.os }}-${{ hashFiles('package-lock.json') }}

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' 
    
      - name: npm install
        run: npm i

      - name: "Run tests"
        run: npm test
        env:
          EDGE_SQL_CONNECTION_STRING: ${{ secrets.MSSQL }}
          EDGE_USE_CORECLR: 1

      - name: publish test-summary nacOS
        if: runner.os == 'macOS'
        uses: EnricoMi/publish-unit-test-result-action/macos@v2
        with:
          check_run_annotations: 'none'
          check_name: 'test-summary-${{ matrix.os }}'
          files: "junit.xml"

      - name: publish test-summary Linux
        if: runner.os == 'Linux'
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_run_annotations: 'none'
          check_name: 'test-summary-${{ matrix.os }}'
          files: "junit.xml"
          
      - name: publish test-summary Windows
        if: runner.os == 'Windows'
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        with:
          check_run_annotations: 'none'
          check_name: 'test-summary-${{ matrix.os }}'
          files: "junit.xml"
          